### ISSUE TITLE
How to Send Photo

### ISSUE THREAD

**Issue by juancarlospaco** [ba0f3/telebot.nim#10]
**How to Send a Photo as a Photo or Document** :question: 

I read all the source code and Telegram API Doc, but still I dont understand how to use this lib.

Is this supported https://core.telegram.org/bots/api#inputmediaphoto ?
or this lib only sends text ?. Not a queryResult but a photo file on local disk.
Thanks... :cat:

**Comment by ba0f3** [comment]
Ooop, after the completly rewrite I missed file sending functionality. And there is not InputMedia cuz this module support bot api 3.0 only.

I will try to update it asap.

**Comment by juancarlospaco** [comment]
Oh, Now I know why I cant find a way to send a file haha. 

Thanks for the work, is very appreciated, Im doing a Bot with this lib, and already has some basic functionality, and I plan to continue expanding it, for example you sent the bot a `*.nim` file it replies with the crosscompiled binaries.

**Comment by ba0f3** [comment]
awesome, I notice it in telegram group, I will update it as soon as I have spare time.

**Comment by ba0f3** [comment]
fixed in https://github.com/ba0f3/telebot.nim/commit/4233bd9fc138712f6d6e8176d1ad1f1c8f16229e, please checkout https://github.com/ba0f3/telebot.nim/releases/tag/0.3.4
