### ISSUE TITLE
Possible issue when compiling with 2.2.0

### ISSUE THREAD

**Issue by samsamros** [ba0f3/telebot.nim#101]
Compiling with 2.2.0. 
Linux - Arm64

I got the following error both in lines 98 and 131:

```bash
.../telebot-2024.09.10-3c94350e8b88263eed9b060926f229840ad77ba9/telebot/private/utils.nim(98, 23) Error: request to generate code for .compileTime proc: formatName
```
Lines 98 and 131 include the following:

```nim
let jsonKey = formatName(name)
```

which I changed to:

```nim
let jsonKey = static(formatName(name))
```

The program compiled with no error. I'm still debugging several issues arising from updating to 2.2.0, please let me know if this error is specific to my setup

**Comment by inv2004** [comment]
@ba0f3 can you create a new tag, plz ?

**Comment by ba0f3** [comment]
I did, I'm sorry I forgot to make a new release for it
