### ISSUE TITLE
Error while trying to compile example

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [ba0f3/telebot.nim#28]
I installed telebot using nimble and was trying to compile example but i'm getting this error:

```
../.nimble/pkgs/telebot-0.5.7.2/telebot/utils.nim(189, 21) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.2/telebot/utils.nim(109, 19) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.2/telebot/utils.nim(172, 23) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.2/telebot/utils.nim(107, 12) Error: undeclared field: 'data'
```

nim version is 0.19.4

**Comment by ba0f3** [comment]
some examples are outdated, which did you compile?

**Comment by Michal-Szczepaniak** [comment]
The one form readme, echo bot

**Comment by ba0f3** [comment]
I assume that you got PassportDate w/ an update. I made a small fix, please pull new version and try again! Thank you!

**Comment by Michal-Szczepaniak** [comment]
I installed telebot@0.5.7.3 but that sadly didn't change anything still same error.

**Comment by ba0f3** [comment]
I need some debug messages, what did it send to server and what server responses

**Comment by Michal-Szczepaniak** [comment]
I'm trying to compile it.


`~/tg $ nim compile bot.nim 
Hint: used config file '/home/mszczepaniak/.choosenim/toolchains/nim-0.19.4/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: bot [Processing]
Hint: telebot [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: types [Processing]
Hint: asyncdispatch [Processing]
Hint: os [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: strformat [Processing]
Hint: macros [Processing]
Hint: posix [Processing]
Hint: ospaths [Processing]
Hint: heapqueue [Processing]
Hint: lists [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: nativesockets [Processing]
Hint: net [Processing]
Hint: sets [Processing]
Hint: selectors [Processing]
Hint: epoll [Processing]
Hint: keyboard [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: streams [Processing]
Hint: parsejson [Processing]
Hint: utils [Processing]
Hint: httpclient [Processing]
Hint: uri [Processing]
Hint: strtabs [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: random [Processing]
Hint: httpcore [Processing]
Hint: asyncnet [Processing]
Hint: asyncfile [Processing]
Hint: logging [Processing]
../.nimble/pkgs/telebot-0.5.7.3/telebot/utils.nim(189, 21) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.3/telebot/utils.nim(109, 19) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.3/telebot/utils.nim(172, 23) template/generic instantiation from here
../.nimble/pkgs/telebot-0.5.7.3/telebot/utils.nim(107, 12) Error: undeclared field: 'data'
`

**Comment by SolitudeSF** [comment]
i have the same error on stable 0.19.4, but it works fine on devel

**Comment by ba0f3** [comment]
thank you, Im compiling Nim 0.19.4...
