### ISSUE TITLE
Error: Exception message: invalid http version, 0x7fdaa227cd50"<html>" 

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [ba0f3/telebot.nim#30]
`Exception message: invalid http version, 0x7fdaa227cd50"<html>"
Exception type: [ProtocolError]`

i compiled example but can't run it it throws straight this error

**Comment by ba0f3** [comment]
did you `slurp secket.key` file? if so, make sure no extra new line in your `secket.key` file

**Comment by Michal-Szczepaniak** [comment]
Yes i did and no there is no extra new line. Same code and same secret.key file works on different machine with different os (older package)

**Comment by ba0f3** [comment]
use `strip` from `strutils` to remove extra characters from secret key
for ex:
```nim
from strutils import strip
const API_KEY = slurp("secret.key").strip()
```

**Comment by Michal-Szczepaniak** [comment]
i have no idea why this worked but this worked

**Comment by ba0f3** [comment]
some time extra `\r` or `\n` or both added to url will makes HTTP requerst malformed. I think its a httpclient's bug.

**Comment by Michal-Szczepaniak** [comment]
but i swear same file works on different pc lol

**Comment by ba0f3** [comment]
strange.. but Im glad it worked ❤️
