### ISSUE TITLE
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]

### ISSUE THREAD

**Issue by jumatberkah** [ba0f3/telebot.nim#38]
Every Time I Tried Your Examples and Write My Own Bot, They always return an unhandled exception.  **Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]**

`(kind: JSMN_STRING, start: 52513, stop: 52516, size: 0, parent: 5466) url
(kind: JSMN_STRING, start: 52529, stop: 52545, size: 0, parent: 5468) Maksudnya Gimana
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/options.nim(181) get
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/asyncfutures.nim(353) read
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/asyncfutures.nim(400) :anonymous
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]
`

My code: https://del.dog/codeconduct.cs

**Comment by ba0f3** [comment]
please enable logging like this. and show me what it got https://github.com/ba0f3/telebot.nim/blob/master/examples/echo_bot.nim#L4

**Comment by jumatberkah** [comment]
> please enable logging like this. and show me what it got https://github.com/ba0f3/telebot.nim/blob/master/examples/echo_bot.nim#L4

Hi, here is the result 
`(kind: JSMN_STRING, start: 53208, stop: 53215, size: 0, parent: 5510) TgBotID
(kind: JSMN_STRING, start: 53264, stop: 53441, size: 0, parent: 5516) \u2063/setwelcome Yey ada member baru!\n\nSelamat datang {mention} \ud83e\udd17\nKamu adalah anggota ke-{count}!\n\n[\ud83d\udc96 Ayra's Bot Project](buttonurl:t.me/AyraBotNews)
(kind: JSMN_STRING, start: 53487, stop: 53498, size: 0, parent: 5525) bot_command
(kind: JSMN_STRING, start: 53535, stop: 53538, size: 0, parent: 5532) url
(kind: JSMN_STRING, start: 53551, stop: 53558, size: 0, parent: 5534) Makasih
DEBUG, [18:36:20] Making request to https://api.telegram.org/bot814183925:AAGU3jYmK3V_tdat6S2cA5z_cEV-NhGokzQ/sendMessage
DEBUG, [18:36:20] Making request to https://api.telegram.org/bot814183925:AAGU3jYmK3V_tdat6S2cA5z_cEV-NhGokzQ/getUpdates
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/options.nim(181) get
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/asyncfutures.nim(353) read
/home/nayef/.choosenim/toolchains/nim-0.20.0/lib/pure/asyncfutures.nim(400) :anonymous
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]`

**Comment by ba0f3** [comment]
first of all revoke your BOT API KEY asap. then try to strip the SECRET_KEY https://github.com/ba0f3/telebot.nim/issues/30#issuecomment-491345779

**Comment by jumatberkah** [comment]
> first of all revoke your BOT API KEY asap. then try to strip the SECRET_KEY [#30 (comment)](https://github.com/ba0f3/telebot.nim/issues/30#issuecomment-491345779) use Nim devel version.. I didnt see log relate to this module yet

Hi there, i've tried all your steps and i've changed to not use secret.key but direct variable, then i already tried revoke and use my other bot token but it didn't work, the second one throw an IOERROR, then i created a new bot with fresh token and it works. Actually i'm still curious how this can happened, i thought that this is nim problem maybe. In short, it worked after i created a new bot

**Comment by ba0f3** [comment]
some other user face'd same problem, maybe you bot's rate is limited, or your bot is banned..

**Comment by ba0f3** [comment]
@jumatberkah can you share me the apikey of the bot had problem? I want to see what was wrong.

telegram me: https://t.me/ba0f3
