### ISSUE TITLE
make the default logs optional

### ISSUE THREAD

**Issue by kaletaa** [ba0f3/telebot.nim#40]
The default logs can be quite annoying while developing a bot, could you make it optional?

By "default logs" I mean these: 
```
(kind: JSMN_STRING, start: 274, stop: 281, size: 0, parent: 34) kaletaa
(kind: JSMN_STRING, start: 233, stop: 240, size: 0, parent: 30) kaletaa
(kind: JSMN_STRING, start: 255, stop: 260, size: 0, parent: 32) private
```

**Comment by ba0f3** [comment]
I think I fixed it already in HEAD

**Comment by kaletaa** [comment]
> I think I fixed it already in HEAD

I just updated the package via nimble and it's still printing them

**Comment by ba0f3** [comment]
alrite, lemme check it again

**Comment by ba0f3** [comment]
make sure you are  using latest version  0.6.5
