### ISSUE TITLE
Deleting messages?

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [ba0f3/telebot.nim#42]
Is it possible to delete message? i tried to use `deleteMessage` but it caused whole bot to freeze and nothing more.

**Comment by ba0f3** [comment]
yes, you can delete messages. make sure your bot has permission to do it

**Comment by Michal-Szczepaniak** [comment]
but is the deleteMessage correct funcion? it seems to freeze my whole bot

**Comment by ba0f3** [comment]
Can you show me your code? `deleteMessage` api works fine for me https://github.com/ba0f3/telebot.nim/blob/master/examples/delete_message.nim

**Comment by Michal-Szczepaniak** [comment]
How do you check though if bot have delete permissions? it's not included in example

**Comment by ba0f3** [comment]
see here: https://github.com/rupansh/nim-tg-manager/blob/ade8068e2ff6ae95902b7d364a7b01e168275237/src/tg_managerpkg/essentials.nim#L43

**Comment by Michal-Szczepaniak** [comment]
Thank you!
