### ISSUE TITLE
Command(s) with '@' bot username does not ignore other bot username.

### ISSUE THREAD

**Issue by jumatberkah** [ba0f3/telebot.nim#44]
My bot username is @XCosmosBot. When i typed command with other bot username, my bot still respond. eg: "/start@XXXBot" it should only respond to XXXBot, but my bot still respond too. Second, command must be in the first order of a message instead of catching command in every message.

![gambar](https://user-images.githubusercontent.com/47906461/62910311-3d2d9c00-bdaa-11e9-8034-7128109c042c.png)

**Comment by ba0f3** [comment]
first, your bot will see every message (including commands) if it is group admin
second, all commands are sent from telegram server as entites, the library doesnt parse commands itself. ref #39

**Comment by jumatberkah** [comment]
> first, your bot will see every message (including other bots' commands) if it is group admin
> second, all commands are sent from telegram server as entites, the library doesnt parse commands itself. ref #39

Hi there, please see [https://github.com/python-telegram-bot/python-telegram-bot/blob/984bea16d197df950c7a752a3888932b0ecb86ad/telegram/ext/commandhandler.py#L169](this)

**Comment by jumatberkah** [comment]
> first, your bot will see every message (including other bots' commands) if it is group admin
> second, all commands are sent from telegram server as entites, the library doesnt parse commands itself. ref #39

Hi there, please see this https://github.com/python-telegram-bot/python-telegram-bot/blob/984bea16d197df950c7a752a3888932b0ecb86ad/telegram/ext/commandhandler.py#L169
