### ISSUE TITLE
Compile issue on latest telebot

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [ba0f3/telebot.nim#45]
/telebot/telebot/webhook.nim(66, 33) template/generic instantiation of `async` from here
.choosenim/toolchains/nim-#devel/lib/pure/asyncmacro.nim(272, 31) Error: 'callbackIter' is not GC-safe as it calls 'handleUpdate'

**Comment by ba0f3** [comment]
Im still using verison 0.6.9 w/ Nim 1.0.4. whats your Nim version? can you show me your snipet?

**Comment by Michal-Szczepaniak** [comment]
I had older nim and updated it to latest using `choosenim devel` and then got lastest telebot using `nimble develop telebot`. For some reason some examples build fine so i will have to investigate further

**Comment by Michal-Szczepaniak** [comment]
The issue exists when you enable threads. Can we reopen it @ba0f3?

**Comment by ba0f3** [comment]
thank you, I will check it again
