### ISSUE TITLE
it compiles well but vscode can't find import 

### ISSUE THREAD

**Issue by fulcanelly** [ba0f3/telebot.nim#62]
![image](https://user-images.githubusercontent.com/53056797/130317574-944722f0-08fa-4bcf-94d4-622d1f46fc11.png)

nim.nimble:
```
# Package

version       = "0.2.0"
author        = "fulcanelly"
description   = "A new awesome nimble package"
license       = "MIT"
srcDir        = "src"
bin           = @["nim"]


requires "nim >= 1.4.2"
requires "telebot"

```

nim.cfg:
```
threads: on
gc: arc
d:ssl
```

**Comment by ba0f3** [comment]
Did you install via nimble? `nimble install telebot`

**Comment by ba0f3** [comment]
Oh wait, this is vscode issue. i dont know why.

**Comment by fulcanelly** [comment]
Ok, after reloading system it seems to be resolved
