### ISSUE TITLE
Compilation failing

### ISSUE THREAD

**Issue by baalajimaestro** [ba0f3/telebot.nim#87]
Log: https://pastebin.com/FzkQqSds

**Comment by ba0f3** [comment]
can you please post your output here? I cant access pastebin.com

**Comment by baalajimaestro** [comment]
[Log](https://github.com/ba0f3/telebot.nim/files/11596149/C7MOar.md)

**Comment by ba0f3** [comment]
what's your Nim version?

**Comment by baalajimaestro** [comment]
```
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release -d:danger
```

**Comment by ba0f3** [comment]
can you show me your code?

**Comment by baalajimaestro** [comment]
https://git.baalajimaestro.me/baalajimaestro/nim-censor-bot

**Comment by ba0f3** [comment]
I don't know why but my nimble can't install w/ norm
