### ISSUE TITLE
Is it posible to skip stale messages?

### ISSUE THREAD

**Issue by mkscs** [ba0f3/telebot.nim#94]
Imagine my bot is offline for an extended period of time and when I restart it I dont want to process old messages. Is this possible?

**Comment by ba0f3** [comment]
there is [cleanUpdates](https://github.com/ba0f3/telebot.nim/blob/817c92a9a885335095365b1399d825e445261c83/src/telebot/private/api.nim#L358C6-L358C18) proc, or you can set `clean = true` when you call [pool](https://github.com/ba0f3/telebot.nim/blob/817c92a9a885335095365b1399d825e445261c83/src/telebot/private/api.nim#L382) or [poolAsync](https://github.com/ba0f3/telebot.nim/blob/817c92a9a885335095365b1399d825e445261c83/src/telebot/private/api.nim#L387) proc
